[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

# Remappings for OpenZeppelin contracts
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Fuzz testing configuration
[fuzz]
runs = 1000

# Invariant testing configuration
[invariant]
runs = 1000
depth = 15
fail_on_revert = false 